//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirOrder
    {
        public int AirOrderID { get; set; }
        public int OrderID { get; set; }
        public int AirID { get; set; }
    
        public virtual Air Air { get; set; }
        public virtual Order Order { get; set; }
    }
}
